# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: anachronism
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog where I keep track of my path through creative anachronism
baseurl: "/anachronism" # the subpath of your site, e.g. /blog
url: "https://anne.loves.technology" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: precisememory
# github_username:  anne-decusatis

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# These are the Github defaults
github: [metadata]
encoding: UTF-8
kramdown:
   input: GFM
   hard_wrap: false
future: true
jailed: false
# use minima theme, as above
# theme: jekyll-theme-primer
gfm_quirks: paragraph_end

# category pages https://kylewbanks.com/blog/creating-category-pages-in-jekyll-without-plugins
collections:
  category:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"